NON_RELATED_WORDS = {
    'new', 'florida', 'texas', 'nyc', 'california', 'says', '2', 'idaho', 'chicago',
    'georgia', 'carolina', 'york', 'city', 'video', 'car', 'home', 'years', 'family',
    'los', 'mom', 'angeles', 'north', 'men', 'state', 'judge', 'officials', '4', 'house',
    'near', 'people', 'sex', 'virginia', 'university', 'court', 'philadelphia', 'fire',
    'subway', 'nypd', '1', 'arizona', 'washington', 'women', 'school', 'teen', '1', '2', '3',
    'mother', 'woman', 'shows', 'girl', 'driver', 'student', 'child', 'search', 'leaves', 'found',
    'man', ':', ',', '(video)', '&', '3', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14',
    '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
    '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46',
    '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62',
    '-', 'father', 'brother', 'sister', 'son', 'daughter', 'husband', 'wife', 'boyfriend', 'girlfriend',
    'boy', '--', '(photo)', '(photos)', 'it\'s', 'don\'t', 'can\'t', 'won\'t', 'didn\'t', 'doesn\'t',
    'i\'m', 'you\'re', 'he\'s', 'she\'s', 'we\'re', 'they\'re', 'i\'ll', 'you\'ll', 'he\'ll', 'she\'ll',
    'we\'ll', 'they\'ll', 'i\'ve', 'you\'ve', 'we\'ve', 'they\'ve', 'i\'d', 'you\'d', 'he\'d', 'she\'d',
    'we\'d', 'they\'d', 'i\'ll', 'you\'ll', 'he\'ll', 'she\'ll', 'we\'ll', 'they\'ll', 'i\'ve', 'you\'ve',
    'we\'ve', 'they\'ve', 'i\'d', 'you\'d', 'he\'d', 'she\'d', 'we\'d', 'they\'d', 'i\'ll', 'you\'ll',
    'he\'ll', 'she\'ll', 'we\'ll', 'they\'ll', 'i\'ve', 'you\'ve', 'we\'ve', 'they\'ve', 'i\'d', 'you\'d',
    'he\'d', 'she\'d', 'we\'d', 'they\'d', 'i\'ll', 'you\'ll', 'he\'ll', 'she\'ll', 'we\'ll', 'they\'ll',
    'i\'ve', 'you\'ve', 'we\'ve', 'they\'ve', 'i\'d', 'you\'d', 'he\'d', 'she\'d', 'we\'d', 'they\'d',
    'i\'ll', 'you\'ll', 'he\'ll', 'she\'ll', 'we\'ll', 'they\'ll', 'i\'ve', 'you\'ve', 'we\'ve', 'they\'ve',
    'i\'d', 'you\'d', 'he\'d', 'she\'d', 'we\'d', 'they\'d', 'i\'ll', 'you\'ll', 'he\'ll', 'she\'ll',
    'we\'ll', 'they\'ll', 'i\'ve', 'you\'ve', 'we\'ve', 'they\'ve', 'i\'d', 'you\'d', 'he\'d', 'she\'d',
    'we\'d', 'they\'d', 'i\'ll', 'you\'ll', 'he\'ll', 'she\'ll', 'we\'ll', 'they\'ll', 'i\'ve', 'you\'ve',
    'san', 'high', 'u.s.', 'ohio', 'photo', 'said', 'yearold'
}